colorize dotsync and install scripts; remove remenants of old color impl

diff --git a/bin/dotfuncs b/bin/dotfuncs
--- a/bin/dotfuncs
+++ b/bin/dotfuncs
@@ -8,7 +8,7 @@ dotsync() {
         moduledir="${dotdir}/${module}"
         installscript="${moduledir}/install.sh"
         if [ ! -d "${moduledir}" ]; then
-            echo >&2 "$(withfg ffb000 '[WARNING]') not a dir: $f"
+            echo >&2 "$(withaf f80 '[WARNING]') not a dir: ${f}"
             continue
         fi
 
@@ -40,12 +40,12 @@ dotsync() {
                 moduledir="${dotdir}/../boxen" # FIXME I expect boxen to be here, but...
                 installscript="${moduledir}/${module}"
                 if [ ! -f "${installscript}" ]; then
-                    echo >&2 "$(withfg ff0000 '[ERROR]') Could not find configuration file for '${module}' at '${moduledir}'."
+                    echo >&2 "$(withaf f00 '[ERROR]') Could not find configuration file for '${module}' at '${moduledir}'."
                     echo >&2 "Skipping ${module}."
                 else
-                    echo >&2 "$(withfg 00d0ff '[INFO]') START including from '${module}'"
+                    echo >&2 "$(withaf 08f '[INFO]') START including from '${module}'"
                     dotsync "${installscript}" "${dotdir}"
-                    echo >&2 "$(withfg 00d0ff '[INFO]') DONE including from '${module}'"
+                    echo >&2 "$(withaf 08f '[INFO]') DONE including from '${module}'"
                 fi
                 ;;
             *)
@@ -85,7 +85,7 @@ dotup() {
             # FIXME I think I don't need to teardown
             # echo >&2 "Preparing clean slate…"
             # if ! dotsync_teardown "${dotdir}"; then
-            #     echo >&2 "$(withfg ffb000 '[WARNING]') Teardown failed, but should never fail."
+            #     echo >&2 "$(withaf f80 '[WARNING]') Teardown failed, but should never fail."
             #     state=FAIL
             #     return 1
             # fi
@@ -96,7 +96,13 @@ dotup() {
                 state=FAIL
             fi
         fi
-        echo >&2 "$(withfg 00d0ff '[INFO]') ${1}: ${state}."
+        case ${state} in
+            ok) echo >&2 "$(withaf 0c0 '[ok]') ${1}" ;;
+            up-to-date) echo >&2 "$(withaf 0c0 '[up-to-date]') ${1}" ;;
+            SKIP) echo >&2 "$(withaf 08f '[SKIP]') ${1}" ;;
+            FAIL) echo >&2 "$(withaf f00 '[FAIL]') ${1}" ;;
+            *) echo >&2 "$(withaf f80 '[WARNING]'): unknown state: ${1}" ;;
+        esac
     )
 }
 
diff --git a/bin/dotsync b/bin/dotsync
--- a/bin/dotsync
+++ b/bin/dotsync
@@ -1,14 +1,17 @@
 #!/bin/sh
 set -e
 
-
-colors="$(dirname "${0}")/colors.sh"
-if [ -f "${colors}" ]; then
-    . "${colors}"
+if which >/dev/null technicolor; then
+    # FIXME when I write this as bash, I can source as expected
+    # FIXME when I run as sh, I have to call technicolor (thus the alias)
+    # FIXME and the newline it shoves out is inconsequential
+    # . "$(which technicolor)"
+    alias withaf=technicolor
 else
-    echo >&2 "$(tput setaf 214)[WARNING]$(tput sgr0) Could not find colors.sh file, expected '${colors}'."
-    withfg() {
-        echo "${2}"
+    echo >&2 "$(tput setaf 3)[WARNING]$(tput sgr0) 'technicolor' not installed. You will not receive further colorized output."
+    withaf() {
+        shift
+        echo -n "${@}"
     }
 fi
 
@@ -16,7 +19,7 @@ dotfuncs="$(dirname "${0}")/dotfuncs"
 if [ -f "${dotfuncs}" ]; then
     . "${dotfuncs}"
 else
-    echo >&2 "$(withfg ff0000 '[ERROR]') Could not find dotfuncs file, expected '${dotfuncs}'."
+    echo >&2 "$(withaf f00 '[ERROR]') Could not find dotfuncs file, expected '${dotfuncs}'."
     exit 127
 fi
 
@@ -26,34 +29,34 @@ if [ -n "${1}" ]; then
 elif [ -d "${HOME}/dotsync" ]; then
     basedir="${HOME}/dotsync"
 else
-    echo >&2 "$(withfg ff0000 '[ERROR]') No dotsync directory found; please specify as first argument (e.g. \`${0} path/to/dotsync\`)."
+    echo >&2 "$(withaf f00 '[ERROR]') No dotsync directory found; please specify as first argument (e.g. \`${0} path/to/dotsync\`)."
     exit 127
 fi
 
 dotdir="${basedir}/dotfiles"
 if [ ! -e "${dotdir}" ]; then
-    echo >&2 "$(withfg ff0000 '[ERROR]') Could not find dotfile directory at '${dotdir}'"
+    echo >&2 "$(withaf f00 '[ERROR]') Could not find dotfile directory at '${dotdir}'"
     exit 127
 elif [ ! -d "${dotdir}" ]; then
-    echo >&2 "$(withfg ff0000 '[ERROR]') Could not find dotfile directory at '${dotdir}'; it exists, but is not a directory."
+    echo >&2 "$(withaf f00 '[ERROR]') Could not find dotfile directory at '${dotdir}'; it exists, but is not a directory."
     exit 127
 fi
 
 boxdir="${basedir}/boxen"
 if [ ! -e "${boxdir}" ]; then
-    echo >&2 "$(withfg ff0000 '[ERROR]') Could not find box-config directory at '${boxdir}'"
+    echo >&2 "$(withaf f00 '[ERROR]') Could not find box-config directory at '${boxdir}'"
     exit 127
 elif [ ! -d "${boxdir}" ]; then
-    echo >&2 "$(withfg ff0000 '[ERROR]') Could not find box-config directory at '${boxdir}'; it exists, but is not a directory."
+    echo >&2 "$(withaf f00 '[ERROR]') Could not find box-config directory at '${boxdir}'; it exists, but is not a directory."
     exit 127
 fi
 
 hostconf="${boxdir}/$(hostname)"
 if [ ! -e "${hostconf}" ]; then
-    echo >&2 "$(withfg ff0000 '[ERROR]') Could not find configuration file for host '$(hostname)' at '${hostconf}'."
+    echo >&2 "$(withaf f00 '[ERROR]') Could not find configuration file for host '$(hostname)' at '${hostconf}'."
     exit 127
 elif [ ! -f "${hostconf}" ]; then
-    echo >&2 "$(withfg ff0000 '[ERROR]') Could not find configuration file for host '$(hostname)' at '${hostconf}'; it is not a regular file."
+    echo >&2 "$(withaf f00 '[ERROR]') Could not find configuration file for host '$(hostname)' at '${hostconf}'; it is not a regular file."
     exit 127
 fi
 
